name: Automation e2e tests
concurrency:
  group: production

on: workflow_dispatch

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm install 
      - name: install latest browsers
        run: npx playwright install 
      - name: run tests
        run: npx playwright test e2e --reporter=html --config playwright.config.js